services:
  postgresdb:
    image: postgres
    container_name: waldo-db
    env_file: ./.env
    restart: unless-stopped
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_PORT:5432
    volumes:
      - db:/var/lib/postgresql/data

  waldo-backend:
    depends_on:
      - postgresdb
    image: waldo-backend
    build: ./
    container_name: waldo-backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_PORT:3000
    environment:
      DATABASE_URL: $DATABASE_URL
      SECRET: $SECRET
      ALLOWED_ORIGINS: $ALLOWED_ORIGINS
    stdin_open: true
    tty: true
    command: >
      sh -c "npx prisma migrate deploy &&
             node app.js"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.waldo-backend.rule=Host(`waldo.localhost`)'
      - 'traefik.http.routers.waldo-backend.entrypoints=web'

volumes:
  db:
