services:
  postgresdb:
    image: postgres
    container_name: waldo_db
    env_file: ./.env
    restart: unless-stopped
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_PORT:5432
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    build: ./
    container_name: waldo_backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_PORT:3000
    environment:
      DATABASE_URL: $DATABASE_URL
      SECRET: $SECRET
      ALLOWED_ORIGINS: $ALLOWED_ORIGINS
    stdin_open: true
    tty: true
    command: >
      sh -c "npx prisma migrate deploy &&
             node app.js"

volumes:
  db:
